### ISSUE TITLE
Input Field Loses Focus During Movie Search

### ISSUE THREAD

**Issue by ankitshiwakoti** [shop2008/movie-recommendation-app#1]
When trying to search for a movie in the app (e.g., "Wall-E"), the input field loses focus after each word or letter is typed, making it difficult to complete the search. This issue disrupts the user experience by forcing the user to click back into the input field after every keystroke or word entry.

Steps to Reproduce:

Navigate to the movie recommendation search page.
Click on the search input field and start typing a movie name (e.g., "Wall-E").
Notice that after typing each word (or sometimes each letter), the input field loses focus.
The user has to manually click back into the field to continue typing.
Expected Behavior: The input field should retain focus while the user is typing, allowing them to complete the movie name without interruptions.

Observed Behavior: The input field loses focus after typing each word or character, which disrupts the typing process.

Environment:

Device: [ Laptop, Mobile]

**Comment by shop2008** [comment]
Thanks for the feedback, the issue now has been fixed
